- exam 1)  2, 1 을 입력해서 예측하자.
- exam 1-1)  1,0,0,0 을 입력해서 예측하자. exam 1)  예제 샘플링 으로  
========================================================
- exam 2) 2, 1 을 입력해서 예측하자.   - 텐서로 모델을 생성해서 해보자.

In [2]:
import tensorflow as tf
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [3]:
input_data = np.array([ [1, 1], [4, 3] ])
target_data = np.array([ 0, 1 ])

In [4]:
input_nodes = 2    # 입력노드 
hidden_nodes = 2   # 은닉노드 
output_nodes = 1   # 출력노드

In [6]:
W2 = np.random.rand(input_nodes, hidden_nodes) 
b2 = np.random.rand(hidden_nodes) 
W3 = np.random.rand(hidden_nodes, output_nodes) 
b3 = np.random.rand(output_nodes) 
print("W2 = ", W2, ", W2.shape = ", W2.shape) 
print("b2 = ", b2, ", b2.shape = ", b2.shape) 
print("W3 = ", W3, ", W3.shape = ", W3.shape) 
print("b3 = ", b3, ", b3.shape = ", b3.shape)

W2 =  [[0.72645733 0.48347171]
 [0.28081274 0.32958424]] , W2.shape =  (2, 2)
b2 =  [0.06346058 0.48029504] , b2.shape =  (2,)
W3 =  [[0.22264507]
 [0.8103985 ]] , W3.shape =  (2, 1)
b3 =  [0.75508316] , b3.shape =  (1,)


In [60]:
from tensorflow.keras.models import Sequential # 순차모델 생성하겠다.
from tensorflow.keras.layers import Dense

data = input_data
labels = target_data

# 모델 구성하기
model = Sequential()

# 입력 레이어와 히든 레이어를 쌓는 단순한 모델
model.add(Dense(1, input_dim = 2, activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [61]:
model.compile('rmsprop', 'mse', metrics = ['acc'])

In [63]:
model.fit(data, labels, epochs = 200)

Epoch 1/200
1/1 [==============================] - 0s 364ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 5ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 11/200
1/1 [===================

1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 169/200
1/1 [==============================] - 0s 2ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 170/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 171/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 172/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 173/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 174/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 175/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 176/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 177/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.0000e+00
Epoch 178/200
1/1 [===============

In [64]:
#7. 데이터 예측

test = np.random.rand(200,2)
predict = np.argmax(model.predict(test), axis = 1)
real = (np.sum(test, axis = 1) > 2.5) *1
print(sum(predict ==real) / 200.0)

7/7 [==============================] - 0s 1ms/step
1.0


In [65]:
from tensorflow.keras.models import Sequential # 순차모델 생성하겠다.
from tensorflow.keras.layers import Dense


input_data = np.array([[1,2,3,4], [0,1,2,0], [0,0,1,0]])
target_data = np.array([0,1,0])

data = input_data
labels = target_data

# 모델 구성하기
model = Sequential()

# 입력 레이어와 히든 레이어를 쌓는 단순한 모델
model.add(Dense(1, input_dim = 4, activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [69]:
model.compile('rmsprop', 'mse', metrics = ['acc'])

In [70]:
model.fit(data, labels, epochs = 200)

Epoch 1/200
1/1 [==============================] - 0s 370ms/step - loss: 0.2500 - acc: 0.3333
Epoch 2/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.3333
Epoch 3/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.3333
Epoch 4/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.3333
Epoch 5/200
1/1 [==============================] - 0s 5ms/step - loss: 0.2500 - acc: 0.3333
Epoch 6/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.3333
Epoch 7/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.3333
Epoch 8/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.3333
Epoch 9/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.3333
Epoch 10/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.3333
Epoch 11/200
1/1 [==============================] - 0s 4ms/step - loss: 0.250

1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.6667
Epoch 177/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.6667
Epoch 178/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.6667
Epoch 179/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.6667
Epoch 180/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.6667
Epoch 181/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.6667
Epoch 182/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.6667
Epoch 183/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.6667
Epoch 184/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2500 - acc: 0.6667
Epoch 185/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2500 - acc: 0.6667
Epoch 186/200
1/1 [==============================] - 0s 3ms/step - loss: 0

In [71]:
#7. 데이터 예측

test = np.random.rand(200,4)
predict = np.argmax(model.predict(test), axis = 1)
real = (np.sum(test, axis = 1) > 2.5) *1
print(sum(predict ==real) / 200.0)

7/7 [==============================] - 0s 838us/step
0.785


In [93]:
from tensorflow.keras.models import Sequential # 순차모델 생성하겠다.
from tensorflow.keras.layers import Dense


input_data = np.array([[1,2]])
target_data = np.array([1])

data = input_data
labels = target_data

# 모델 구성하기
model = Sequential()

# 입력 레이어와 히든 레이어를 쌓는 단순한 모델
model.add(Dense(1, input_dim = 2, activation = 'relu'))

model.add(Dense(3, activation = 'sigmoid'))

In [94]:
model.compile('rmsprop', 'mse', metrics = ['acc'])

In [95]:
model.fit(data, labels, epochs = 200)

Epoch 1/200
1/1 [==============================] - 0s 371ms/step - loss: 0.2763 - acc: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2745 - acc: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2733 - acc: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2722 - acc: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2712 - acc: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2704 - acc: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 3ms/step - loss: 0.2695 - acc: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2688 - acc: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2680 - acc: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 4ms/step - loss: 0.2673 - acc: 0.0000e+00
Epoch 11/200
1/1 [===================

1/1 [==============================] - 0s 3ms/step - loss: 0.1918 - acc: 0.0000e+00
Epoch 169/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1915 - acc: 0.0000e+00
Epoch 170/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1912 - acc: 0.0000e+00
Epoch 171/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1909 - acc: 0.0000e+00
Epoch 172/200
1/1 [==============================] - 0s 4ms/step - loss: 0.1905 - acc: 0.0000e+00
Epoch 173/200
1/1 [==============================] - 0s 4ms/step - loss: 0.1902 - acc: 0.0000e+00
Epoch 174/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1899 - acc: 0.0000e+00
Epoch 175/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1896 - acc: 0.0000e+00
Epoch 176/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1893 - acc: 0.0000e+00
Epoch 177/200
1/1 [==============================] - 0s 4ms/step - loss: 0.1890 - acc: 0.0000e+00
Epoch 178/200
1/1 [===============

In [96]:
#7. 데이터 예측

test = np.random.rand(200,2)
predict = np.argmax(model.predict(test), axis = 1)
real = (np.sum(test, axis = 1) > 2.5) *1
print(sum(predict ==real) / 200.0)

7/7 [==============================] - 0s 1000us/step
1.0


In [81]:
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_30 (Dense)            (None, 1)                 3         
                                                                 
 dense_31 (Dense)            (None, 3)                 6         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [82]:
weights, biases = model.layers[0].get_weights()
print(weights)
print(biases)

print("-"*10)
weights, biases = model.layers[1].get_weights()
print(weights)
print(biases)

[[-0.16262782]
 [ 0.06965017]]
[0.]
----------
[[-1.1841341  -0.35709208  0.5614563 ]]
[0.20814402 0.20814402 0.20814402]


In [83]:
print(model(data))

tf.Tensor([[0.55184895 0.55184895 0.55184895]], shape=(1, 3), dtype=float32)
